export const INTL = {
  COLUMNS: {
    INDUSTRY: "Отрасль",
    PLATFORM: "Платформы",
    SERVICES: "Услуги",
    LANGUAGES: "Языки",
  },
  COLUMN_VALUES: {
    INDUSTRY: {
      BI: "BI-отчеты",
      ORDERS: "Гос. заказ",
      ENERGY: "Энергетика",
      EDUCATION: "Образование",
      FINTECH: "Финтех",
      LIFESTYLE: "Образ жизни",
      MEDICINE: "Медицина",
      ECOMMECE: "E-commerce",
      SECURITY: "Безопасность",
      INTERTAIMENT: "Развлечения",
      CARTOGRAPHY: "Картография",
    },
    PLATFORM: {
      ANDROID: "Android",
      CHAT: "Chat-system",
      TELEGRAM: "Telegram",
      BACKEND: "Backend",
      WINDOWS: "Windows",
      PANEL: "Панель управления",
      WEB: "Web",
      IOS: "iOS",
    },
    SERVICES: {
      RELEASE: "Релиз",
      DEVOPS: "Сопровождение",
      DESIGN: "Дизайн",
      TEST: "Тестирование",
      DEV: "Разработка",
      PROJECT: "Предпроектная деятельность",
      ANALITICS: "Аналитика",
      PSI: "Приемка",
    },
    LANGUAGES: {
      NODE: "Node.JS",
      JAVA: "Java",
      XAMARIN: "Xamarin",
      WP: "Wordpress",
      ANG: "Drupal 8, Angular",
      ASP: "ASP.NET Core, Azure",
      BI: "MS Power BI",
      BITRIX: "1C-Битрикс",
      OC: "Objective-C",
      UMP: "C#, UWP",
      PYTHON: "Python",
      PHP: "PHP",
      KOTLIN: "Kotlin",
      MODX: "MODX",
      SWIFT: "Swift",
      PG: "PhoneGap",
      REACT: "React",
      JAVA_KOTLIN: "Java, Kotlin",
      CORDOVA: "Cordova",
      CPP: "C++",
    },
  },
};
